version: "2.1"

#docker image  https://dockerfile.readthedocs.io/en/latest/content/DockerImages/
services:
  nginx:
      container_name: nginx
      image: webdevops/nginx:centos-7
      restart: always
      links:
        - php56
        - php74
      ports:
        - "80:80"
        - "443:443"
      tty: true
      volumes:
        - ./nginx:/opt/docker/etc/nginx
      networks:
        default_net:
          ipv4_address: 172.173.0.2
  php56:
    image: webdevops/php:5.6
    container_name: php56
    restart: always
    volumes:
      - /opt/htdocs:/opt/htdocs:cached
      - ./php/php56/fpm:/opt/docker/etc/php/fpm
    extra_hosts:
      - "www.demo.com:172.173.0.2"
    networks:
      default_net:
        ipv4_address: 172.173.0.3
  php74:
    image: webdevops/php:7.4
    container_name: php74
    restart: always
    volumes:
        - /opt/htdocs:/opt/htdocs:cached
        - ./php/php74/fpm:/opt/docker/etc/php/fpm
    extra_hosts:
        - "www.demo.com:172.173.0.2"
    networks:
        default_net:
          ipv4_address: 172.173.0.4

networks:
  default_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
      - subnet: 172.173.0.0/24
        gateway: 172.173.0.1
